name = "xdf-dashboard-data"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV命名空间绑定（创建后自动填入id）
[[kv_namespaces]]
binding = "DASHBOARD_KV"
id = "a9a4517010094107b4502cc688b2c2a1"

# 环境变量
[vars]
AUTH_PASSWORD = "27rk"

# 免费套餐
# Workers Free: 100,000 requests/day, 10ms CPU time
# KV Free: 1GB storage, 100,000 reads/day
